--> 1. -> 1.1. open_application.open_application_url(parameters)
--> 1. -> 1.1. login.verify_view()
--> 1.1. -> 1.1.1. login.click_register()
--> 1.1. -> 1.1.1. register.verify_view()
--> 1.1.1. -> 1.1. register.register(parameters)
--> 1. -> 1.1. open_application.open_application_url(parameters)
--> 1. -> 1.1. login.verify_view()
--> 1.1. -> 1.1.2. login.sign_in(parameters)
--> 1.1. -> 1.1.2. workspace.verify_view()
--> 1.1.2. -> 1.1. workspace.log_out()
--> 1. -> 1.1. open_application.open_application_url(parameters)
--> 1. -> 1.1. login.verify_view()
--> 1.1. -> 1.1.2. login.sign_in(parameters)
--> 1.1. -> 1.1.2. workspace.verify_view()
--> 1.1.2. -> 1.1.2.1. workspace.create_board()
--> 1.1.2. -> 1.1.2.1. create_board.verify_view()
--> 1.1.2.1. -> 1.1.2.__1 create_board.create(parameters)
--> 1.1.2. -> 1.1.2.4. workspace.enter_board(parameters)
--> 1.1.2. -> 1.1.2.4. board.verify_view()
--> EXCEPTION: 
expected: 'Create ticket', actual 'Create board'
Traceback (most recent call last):
  File "model_graph_runner.py", line 426, in webframework.extension.model_graph_runner.model_graph_runner.ModelGraphRunner._run_method (webframework\extension\model_graph_runner\model_graph_runner.c:7202)
  File "C:\Users\g2516\Desktop\Tests\Contriboard\pagemodel\board.py", line 37, in verify_view
    self.verify_text(self.CREATE_TICKET_BUTTON, u'Create ticket')
  File "C:\Python27\Lib\site-packages\ixonos-visual-test\webframework\extension\util\common_utils.py", line 1583, in verify_text
    CommonMethodsHelpers.assert_equal(value, self._wm.get_text(element))
  File "common_methods_helpers.py", line 76, in webframework.extension.util.common_methods_helpers.CommonMethodsHelpers.assert_equal (webframework\extension\util\common_methods_helpers.c:1953)
  File "C:\Python27\lib\unittest\case.py", line 511, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python27\lib\unittest\case.py", line 922, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Python27\lib\unittest\case.py", line 408, in fail
    raise self.failureException(msg)
AssertionError: 
expected: 'Create ticket', actual 'Create board'
